# Generated by Django 4.1.2 on 2022-10-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_form_filled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'CustomUser'},
        ),
        migrations.AlterModelOptions(
            name='mentee',
            options={'verbose_name': 'Mentee'},
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Mentor'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_mentee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
