# Generated by Django 4.1.2 on 2022-10-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_alter_mentee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='starrating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mentor',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
