# Generated by Django 4.1.2 on 2022-10-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_mentee_pending_requests_alter_mentee_mentor_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='mentor_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_assigned_set', to='users.mentor'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='pending_requests',
            field=models.ManyToManyField(blank=True, null=True, to='users.mentor'),
        ),
    ]
