# Generated by Django 4.1.2 on 2022-10-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_mentee_mentor_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='pending_requests',
            field=models.ManyToManyField(blank=True, to='users.mentor'),
        ),
    ]
