# Generated by Django 4.1.2 on 2022-11-01 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_pendingmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('mentee', models.ManyToManyField(blank=True, to='users.mentor')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_notes_set', to='users.mentor')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
