# Generated by Django 4.1.2 on 2022-11-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notes_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='mentee',
            field=models.ManyToManyField(blank=True, to='users.mentee'),
        ),
    ]
